(define (problem ANOI-3-7)
	(:domain ANOI)
	(:objects G M R - tower A B C D E F H - rondelle)
	(:INIT 
		(ontower A G)
		(ontower B G)
		(ontower C G)
		(ontower D G)
		(ontower E G)
		(ontower F G)
        (ontower H G)
		(on B A)
		(on C B)
		(on D C)
		(on E D)
		(on F E)
		(on H F)
		(clearUnder A)
		(clearAbove H)
		(towerclear M)
		(towerclear R)
	)
	(:goal (AND (ontower A R) (on B A) (on C B) (on B A) (on C B) (on D C) (on E D) (on F E) (on H F)))
)