(define (problem ANOI-3-3)
	(:domain ANOI)
	(:objects G M D - tower A B C - rondelle)
	(:INIT 
		(ontower A G)
		(ontower B G)
		(ontower C G)
		(on B A)
		(on C B)
		(clearUnder A)
		(clearAbove C)
		(towerclear M)
		(towerclear D)
	)
	(:goal (AND (ontower A D) (on B A) (on C B)))
)