(define (problem ROBOTPARTY) (:domain KROBOT)
	(:objects A B C D E F G H I J K L - node Z Y X W V U T S R - palet)
	(:init
		(robotOnNode B)
		(robotFree)
		(paletOnNode Z D)
		(paletOnNode Y E)
		(paletOnNode X F)
		(paletOnNode W G)
		(paletOnNode V H)
		(paletOnNode U I)
		(paletOnNode T J)
		(paletOnNode S K)
		(paletOnNode R L)
		(connected A B)
		(connected A D)
		(connected B A)
		(connected B C)
		(connected B E)
		(connected C B)
		(connected C F)
		(connected D A)
		(connected D E)
		(connected D G)
		(connected E B)
		(connected E D)
		(connected E F)
		(connected E H)
		(connected F C)
		(connected F E)
		(connected F I)
		(connected G D)
		(connected G H)
		(connected G J)
		(connected H E)
		(connected H G)
		(connected H I)
		(connected H K)
		(connected I F)
		(connected I H)
		(connected I L)
		(connected J G)
		(connected J K)
		(connected K H)
		(connected K J)
		(connected K L)
		(connected L I)
		(connected L K)
		(nodeInCamp A)
		(nodeInCamp B)
		(nodeInCamp C)
	)
	(:goal (and
			(paletInCamp Z)
			(paletInCamp Y)
			(paletInCamp X)
			(paletInCamp W)
			(paletInCamp V)
			(paletInCamp U)
			(paletInCamp T)
			(paletInCamp S)
			(paletInCamp R)
		)
	)
)
