(define (problem ROBOTPARTY) (:domain KROBOT)
	(:objects A D E F G H I J K L - node Z Y X W V U T S R - palet)
	(:init
		(robotOnNode A)
		(robotFree)
		(paletOnNode Z D)
		(paletOnNode Y E)
		(paletOnNode X F)
		(paletOnNode W G)
		(paletOnNode V H)
		(paletOnNode U I)
		(paletOnNode T J)
		(paletOnNode S K)
		(paletOnNode R L)
		(connected A D)
		(connected A E)
		(connected A F)
		(connected D E)
		(connected D G)
		(connected E F)
		(connected E H)
		(connected F I)
		(connected G H)
		(connected G J)
		(connected H I)
		(connected H K)
		(connected I L)
		(nodeInCamp A)
	)
	(:goal 
		(and
			(paletInCamp Z)
			(paletInCamp Y)
			(paletInCamp X)
			(paletInCamp W)
			(paletInCamp V)
			(paletInCamp U)
			(paletInCamp T)
			(paletInCamp S)
			(paletInCamp R)
		)
	)
)
